- name: Directory is present
  file:
    path=/data/db
    state=directory
  tags: [build-service]

- name: Container is running
  docker:
    name=build-service
    image=paulvelzeboer/build-service
    ports=8080:8080
    volumes=/data/db:/data/db
  tags: [build-service]
